micronaut:
  application:
    name: micronautApi
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mydb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'my-secret-pw'
#    schema-generate: CREATE_DROP
#    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
